---
- name: change service state
  hosts: all
  vars:
   - service_name: httpd
   - service_state: started
  tasks:
   - name: change service state as per requirement
     service:
      name: "{{ service_name }}"
      state: "{{ service_state }}"
